"""
web_viz.py - Generate styled HTML report for cloud removal results.
Usage: python web_viz.py --input-dir outputs --output report.html
"""
import os
import argparse
import base64
import json
from pathlib import Path


def img_to_base64(path):
    with open(path, "rb") as f:
        return base64.b64encode(f.read()).decode("utf-8")


def generate_report(input_dir, output_path):
    input_dir = Path(input_dir)

    # Find all images grouped by subfolder
    sections = {}
    for img_path in sorted(input_dir.rglob("*.png")):
        rel = img_path.relative_to(input_dir)
        folder = rel.parts[0] if len(rel.parts) > 1 else "root"
        if folder not in sections:
            sections[folder] = []
        b64 = img_to_base64(str(img_path))
        sections[folder].append({
            "name": rel.stem,
            "path": str(rel),
            "data": f"data:image/png;base64,{b64}",
        })

    # Try to load metrics
    metrics = None
    loss_path = input_dir / "synthetic" / "loss_history.npy"
    if loss_path.exists():
        import numpy as np
        history = np.load(str(loss_path), allow_pickle=True)
        last = history[-1] if len(history) > 0 else {}
        metrics = {
            "train_loss": f"{last.get('train', 0):.6f}",
            "val_loss": f"{last.get('val', 0):.6f}",
            "val_psnr": f"{last.get('val_psnr', 0):.2f}",
            "epochs": str(len(history)),
        }

    # Build HTML
    metric_cards = ""
    if metrics:
        metric_cards = f"""
        <div class="metrics">
            <div class="metric-card"><div class="metric-value">{metrics['val_psnr']} dB</div><div class="metric-label">Val PSNR</div></div>
            <div class="metric-card"><div class="metric-value">{metrics['val_loss']}</div><div class="metric-label">Val Loss</div></div>
            <div class="metric-card"><div class="metric-value">{metrics['train_loss']}</div><div class="metric-label">Train Loss</div></div>
            <div class="metric-card"><div class="metric-value">{metrics['epochs']}</div><div class="metric-label">Epochs</div></div>
        </div>
        """

    image_sections = ""
    for folder, imgs in sections.items():
        cards = ""
        for img in imgs:
            cards += f'<div class="img-card"><h4>{img["name"]}</h4><img src="{img["data"]}" alt="{img["name"]}"/></div>\n'
        image_sections += f'<div class="section"><h2>{folder}</h2><div class="img-grid">{cards}</div></div>\n'

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Cloud Removal Report</title>
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ font-family: 'Segoe UI', system-ui, sans-serif; background: #f5f6fa; color: #2c3e50; }}
.container {{ max-width: 1200px; margin: 0 auto; padding: 30px 20px; }}
h1 {{ font-size: 2em; border-bottom: 3px solid #3498db; padding-bottom: 12px; margin-bottom: 30px; }}
h2 {{ font-size: 1.4em; color: #34495e; margin: 25px 0 15px; }}
.metrics {{ display: flex; gap: 15px; flex-wrap: wrap; margin: 20px 0 30px; }}
.metric-card {{ background: white; border-radius: 10px; padding: 20px 30px; text-align: center;
    box-shadow: 0 2px 8px rgba(0,0,0,0.08); min-width: 140px; }}
.metric-value {{ font-size: 1.8em; font-weight: bold; color: #2980b9; }}
.metric-label {{ font-size: 0.85em; color: #7f8c8d; margin-top: 4px; }}
.section {{ background: white; border-radius: 10px; padding: 20px; margin: 20px 0;
    box-shadow: 0 2px 8px rgba(0,0,0,0.08); }}
.img-grid {{ display: flex; gap: 15px; flex-wrap: wrap; }}
.img-card {{ flex: 1; min-width: 250px; max-width: 400px; }}
.img-card h4 {{ font-size: 0.9em; color: #7f8c8d; margin-bottom: 8px; }}
.img-card img {{ width: 100%; border-radius: 6px; border: 1px solid #ecf0f1; }}
.footer {{ text-align: center; margin-top: 40px; font-size: 0.85em; color: #95a5a6; }}
@media print {{ .no-print {{ display: none; }} body {{ background: white; }} }}
</style>
</head>
<body>
<div class="container">
<h1>Cloud Removal for LISS-IV &mdash; Results Report</h1>
{metric_cards}
{image_sections}
<div class="footer">Generated by Cloud Removal Pipeline | Hackathon 2026</div>
</div>
</body>
</html>"""

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"Report written to {output_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate HTML report")
    parser.add_argument("--input-dir", default="outputs", help="Directory with output images")
    parser.add_argument("--output", default="report.html", help="Output HTML path")
    args = parser.parse_args()
    generate_report(args.input_dir, args.output)
